server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: assessment
    password: 12345678aA
    url: jdbc:mysql://rm-bp10k0w05n83wz4af0o.mysql.rds.aliyuncs.com:3306/assessment
#    username: root
#    password: 111111
#    url: jdbc:mysql://localhost:3306/bbsend?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      example:
        mapper:
          debug
